# Generated by Django 5.0.14 on 2026-07-03 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('searching', 'Searching For Worker'), ('accepted', 'Worker Accepted'), ('on_the_way', 'Worker On The Way'), ('arrived', 'Worker Arrived'), ('verified', 'QR Verified'), ('in_progress', 'Work Started / Repair In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='searching', max_length=50)),
                ('qr_code_value', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('before_photo', models.ImageField(blank=True, null=True, upload_to='bookings/before/')),
                ('after_photo', models.ImageField(blank=True, null=True, upload_to='bookings/after/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicecategory')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MajorRepairApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_repairs', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='RepairToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('reached_workshop', 'Reached Workshop'), ('inspection', 'Inspection'), ('repair_started', 'Repair Started'), ('waiting_parts', 'Waiting For Parts'), ('repair_completed', 'Repair Completed'), ('returning', 'Returning'), ('delivered', 'Delivered')], default='reached_workshop', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repair_token', to='bookings.booking')),
            ],
        ),
    ]
