# Generated by Django 5.0.14 on 2026-07-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('slot', 'Slot-Based Service'), ('instant', 'Instant Service (10-40 mins)')], default='slot', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
