# Generated by Django 5.0.14 on 2026-07-04 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_type_alter_booking_preferred_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice_photo',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/invoices/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='optional_video',
            field=models.FileField(blank=True, null=True, upload_to='bookings/videos/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='spare_part_photo',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/parts/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching For Worker'), ('accepted', 'Worker Accepted'), ('on_the_way', 'Worker On The Way'), ('arrived', 'Worker Arrived'), ('verified', 'QR Verified'), ('inspection', 'Inspection'), ('repair_started', 'Repair Started'), ('repair_completed', 'Repair Completed'), ('waiting_approval', 'Waiting For Customer Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='searching', max_length=50),
        ),
        migrations.AlterField(
            model_name='repairtoken',
            name='status',
            field=models.CharField(choices=[('item_received', 'Item Received'), ('reached_workshop', 'Reached Workshop'), ('inspection', 'Inspection'), ('repair_started', 'Repair Started'), ('waiting_parts', 'Waiting For Parts'), ('repair_completed', 'Repair Completed'), ('returning', 'Returning'), ('delivered', 'Delivered')], default='item_received', max_length=50),
        ),
        migrations.CreateModel(
            name='BookingRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rejections', to='bookings.booking')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rejections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('worker', 'booking')},
            },
        ),
    ]
