# Generated by Django 5.0.14 on 2026-07-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_invoice_photo_booking_optional_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
