# Generated by Django 5.0.14 on 2026-07-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='preferred_time',
        ),
    ]
