# Generated by Django 5.0.14 on 2026-07-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_booking_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching For Worker'), ('accepted', 'Worker Accepted'), ('on_the_way', 'Worker On The Way'), ('arrived', 'Worker Arrived'), ('verified', 'QR Verified'), ('inspection', 'Inspection'), ('repair_started', 'Repair Started'), ('repair_completed', 'Repair Completed'), ('waiting_approval', 'Waiting For Customer Approval'), ('WAITING_FOR_CASH_CONFIRMATION', 'Waiting For Cash Confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='searching', max_length=50),
        ),
    ]
