# Generated by Django 5.0.14 on 2026-07-05 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('recipient_type', models.CharField(choices=[('all_customers', 'All Customers'), ('all_captains', 'All Captains'), ('individual_customer', 'Individual Customer'), ('individual_captain', 'Individual Captain')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
