# Generated by Django 5.0.14 on 2026-08-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_workerprofile_dob_workerprofile_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy')], default='AVAILABLE', max_length=20),
        ),
    ]
