# Generated by Django 5.0.14 on 2026-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='supplier_invoice',
            field=models.FileField(blank=True, null=True, upload_to='supplier_invoices/'),
        ),
    ]
