# Generated by Django 5.0.14 on 2026-07-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Workizo', max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('contact_details', models.TextField(blank=True, null=True)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('support_email', models.EmailField(default='support@workizo.com', max_length=254)),
                ('support_phone', models.CharField(default='+919876543210', max_length=15)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='base_labour_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
