"""
Payment state, amount, Razorpay signature, and cash payment validations.
"""

import hmac
import hashlib
from decimal import Decimal
from typing import Union, List, Any
from rest_framework.exceptions import ValidationError, PermissionDenied, NotFound


def validate_payment_amount(amount: Union[Decimal, float, int, str]) -> Decimal:
    """
    Validate payment amount is positive decimal value.

    :param amount: Numeric amount.
    :return: Decimal amount.
    :raises ValidationError: If amount is less than or equal to zero.
    """
    try:
        dec_amount = Decimal(str(amount))
    except Exception:
        raise ValidationError({"amount": "Payment amount must be a valid numeric value."})

    if dec_amount <= Decimal("0.00"):
        raise ValidationError({"amount": "Payment amount must be greater than 0."})

    return dec_amount


def validate_payment_status(payment: Any, allowed_statuses: List[str]) -> None:
    """
    Validate payment object status against allowed state list.

    :param payment: Payment object.
    :param allowed_statuses: Allowed status strings.
    :raises ValidationError: If status is invalid.
    """
    if not payment:
        raise NotFound("Payment record not found.")

    status_str = str(getattr(payment, 'status', ''))
    if status_str not in allowed_statuses:
        allowed_fmt = ", ".join([f"'{s}'" for s in allowed_statuses])
        raise ValidationError({
            "detail": f"Payment status '{status_str}' is invalid for this operation. Allowed: {allowed_fmt}."
        })


def validate_duplicate_payment(booking: Any) -> None:
    """
    Prevent duplicate successful payment creation for a booking.

    :param booking: Booking object.
    :raises ValidationError: If booking already has a completed payment.
    """
    if not booking:
        raise NotFound("Booking not found.")

    from billing.models import Payment
    PAID_STATUSES = ['PAID', 'COMPLETED', 'success', 'Paid', 'Completed']
    existing_paid = Payment.objects.filter(booking=booking, status__in=PAID_STATUSES).exists()
    if existing_paid:
        raise ValidationError({"detail": "This booking already has a verified, completed payment."})


def validate_cash_confirmation(payment: Any, user: Any) -> None:
    """
    Validate that user (assigned worker or admin) can confirm cash collection.

    :param payment: Payment object.
    :param user: User object confirming cash.
    :raises PermissionDenied: If user is not authorized.
    :raises ValidationError: If payment method is not cash or already confirmed.
    """
    if not user or not user.is_authenticated:
        raise PermissionDenied("Authentication required.")

    booking = getattr(payment, 'booking', None)
    if not booking:
        raise NotFound("Booking reference missing on payment.")

    if not (user.is_staff or getattr(user, 'role', '') == 'admin' or booking.worker_id == user.id):
        raise PermissionDenied("Only assigned captain or admin can verify cash payment.")

    payment_method = str(getattr(payment, 'payment_method', '')).lower()
    if payment_method not in ['cash', 'cod']:
        raise ValidationError({"detail": "Only cash/COD payments can be confirmed manually."})


def validate_razorpay_signature(razorpay_order_id: str, razorpay_payment_id: str, razorpay_signature: str, secret: str) -> None:
    """
    Validate HMAC SHA256 signature generated by Razorpay.

    :param razorpay_order_id: Razorpay order ID.
    :param razorpay_payment_id: Razorpay payment ID.
    :param razorpay_signature: Signature received from frontend/webhook.
    :param secret: Razorpay API Key Secret.
    :raises ValidationError: If signature verification fails.
    """
    if not razorpay_order_id or not razorpay_payment_id or not razorpay_signature:
        raise ValidationError({"detail": "Razorpay order ID, payment ID, and signature are required."})

    if not secret:
        raise ValidationError({"detail": "Razorpay secret key is not configured."})

    msg = f"{razorpay_order_id}|{razorpay_payment_id}".encode('utf-8')
    generated_signature = hmac.new(
        secret.encode('utf-8'),
        msg,
        hashlib.sha256
    ).hexdigest()

    if generated_signature != razorpay_signature:
        raise ValidationError({"detail": "Razorpay payment signature verification failed."})


def validate_invoice_payment(bill: Any) -> None:
    """
    Validate that an invoice/bill is approved and unpaid before initiating payment.

    :param bill: Bill model instance.
    :raises ValidationError: If bill is unapproved or already paid.
    """
    if not bill:
        raise NotFound("Invoice/Bill not found.")

    if not getattr(bill, 'is_approved', False):
        raise ValidationError({"detail": "Invoice must be approved before payment can be processed."})

    from billing.models import Payment
    PAID_STATUSES = ['PAID', 'COMPLETED', 'success', 'Paid', 'Completed']
    if Payment.objects.filter(booking=bill.booking, status__in=PAID_STATUSES).exists():
        raise ValidationError({"detail": "Invoice has already been paid."})
